---
title: "Repeatability of thermal plasticity"
author: "Fonti Kar, Daniel Noble, Shinichi Nakagawa"
date: "13/07/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load data, echo = FALSE, include = FALSE}
setwd("~/Dropbox/smrrxn/")

rm(list = ls())

library(ggplot2)
library(lme4)

data <- read.csv("data/data_final/mrrxn_final_v2.csv")
```

### Use Boltzmann constant corrected temperature or z-transformed temperature?

```{r boltz, include = TRUE}
model.1.1 <- lmer(z.log.co2pmin ~ inverseK_incb_temp + z.log.mass + (1+inverseK_incb_temp|id) + (1+inverseK_incb_temp|series), data = data)
summary(model.1.1)
AIC(model.1.1) #No AIC diff in z.log.temp and inverseK temp - stick with inverseK temp

model.1.2 <- lmer(z.log.co2pmin ~ z.incb_temp + z.log.mass + (1+z.incb_temp|id) + (1+z.incb_temp|series), data = data)
summary(model.1.2)
AIC(model.1.2) 

model.1.3 <- lmer(z.log.co2pmin ~ z.log.temp + z.log.mass + (1+z.log.temp|id) + (1+z.log.temp|series), data = data)
summary(model.1.3)
AIC(model.1.3)  
```

### Carry-over effects of previous temperatures using Boltzmann constant corrected temperature predictors

```{r carryover, include = TRUE}
#Carry over effects of prior temps 
model.2.1 <- lmer(z.log.co2pmin ~ inverseK_incb_temp + z.log.mass + inverseK_body_temp + (1+inverseK_incb_temp|id) + (1+inverseK_incb_temp|series), data = data)
summary(model.2.1)
AIC(model.2.1) #body_temp results in the lowest AIC, but doesn't account for prior measurement temps.

model.2.2 <- lmer(z.log.co2pmin ~ inverseK_incb_temp + z.log.mass + inverseK_prior_temp1 + (1+inverseK_incb_temp|id) + (1+inverseK_incb_temp|series), data = data)
summary(model.2.2)
AIC(model.2.2) 
plot(model.2.2)
qqnorm(resid(model.2.2))

model.2.3 <- lmer(z.log.co2pmin ~ inverseK_incb_temp + z.log.mass + inverseK_prior_temp2 + (1+inverseK_incb_temp|id) + (1+inverseK_incb_temp|series), data = data)
summary(model.2.3)
AIC(model.2.3) #lower AIC of the two prior_temp variables - stick with this one for final model
plot(model.2.3)
qqnorm(resid(model.2.3)) 
```

### Repeatabilty of reaction norms

```{r rptrxnnorm, include = TRUE}
mod2.3 <- data.frame(VarCorr(model.2.3, comp = "Variance"))

mod2.3[4,4] / (mod2.3[4,4] + mod2.3[1,4]) 

#R slope

mod2.3[5,4] / (mod2.3[5,4] + mod2.3[2,4]) 

#R short term

(mod2.3[4,4] +  mod2.3[1,4]) / (mod2.3[4,4] +  mod2.3[1,4] + mod2.3[7,4]) 

#R long term

mod2.3[4,4] / (mod2.3[4,4] +  mod2.3[1,4] + mod2.3[7,4])
```


### Plotting reaction norms across series using final model.2.3

```{r set up for plot, include = FALSE}
#Trying to plot these reaction norms out by groups of 14 lizards

ids_order <- sort(unique(data$id))
g1 <- ids_order[1:14]
g2 <- ids_order[15:28]
g3 <- ids_order[29:42]

predictors <- c("z.log.co2pmin", "inverseK_incb_temp", "z.log.mass", "inverseK_prior_temp2" , "id" ,"series")

plot.data <- data[complete.cases(data[ , predictors ]),]
plot.data$z.log.co2pm_pred <- predict(model.2.3, type = "response")
plot.data$log.co2pm_pred <- (plot.data$z.log.co2pm_pred * sd(plot.data$log.co2pmin)) + mean(plot.data$log.co2pmin)
plot.data$co2pm_pred <- exp(plot.data$log.co2pm_pred)

g1.dat <- plot.data[plot.data$id %in% g1,]
g2.dat <- plot.data[plot.data$id %in% g2,]
g3.dat <- plot.data[plot.data$id %in% g3,]
```

```{r plot reaction norms, include = TRUE}
#g1
ggplot(g1.dat, aes(y = z.log.co2pm_pred, 
                   x = inverseK_incb_temp,
                   group = id, 
                   colour = id)) +
  geom_point() +
  geom_line() + 
  facet_wrap( ~ samp_period, nrow = 2) +
  theme_bw()   

#g2
ggplot(g2.dat, aes(y = z.log.co2pm_pred, 
                   x = inverseK_incb_temp,
                   group = id, 
                   colour = id)) +
  geom_point() +
  geom_line() + 
  facet_wrap( ~ samp_period, nrow = 2) +
  theme_bw() 

#g3
ggplot(g3.dat, aes(y = z.log.co2pm_pred, 
                   x = inverseK_incb_temp,
                   group = id, 
                   colour = id)) +
  geom_point() +
  geom_line() + 
  facet_wrap( ~ samp_period, nrow = 2) +
  theme_bw() 

```